/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainersIndexRouteImport } from './routes/trainers.index'
import { Route as TrainersIdRouteImport } from './routes/trainers.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainersIndexRoute = TrainersIndexRouteImport.update({
  id: '/trainers/',
  path: '/trainers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainersIdRoute = TrainersIdRouteImport.update({
  id: '/trainers/$id',
  path: '/trainers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/trainers/$id': typeof TrainersIdRoute
  '/trainers/': typeof TrainersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/trainers/$id': typeof TrainersIdRoute
  '/trainers': typeof TrainersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/trainers/$id': typeof TrainersIdRoute
  '/trainers/': typeof TrainersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/trainers/$id' | '/trainers/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/trainers/$id' | '/trainers'
  id: '__root__' | '/' | '/trainers/$id' | '/trainers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TrainersIdRoute: typeof TrainersIdRoute
  TrainersIndexRoute: typeof TrainersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainers/': {
      id: '/trainers/'
      path: '/trainers'
      fullPath: '/trainers/'
      preLoaderRoute: typeof TrainersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainers/$id': {
      id: '/trainers/$id'
      path: '/trainers/$id'
      fullPath: '/trainers/$id'
      preLoaderRoute: typeof TrainersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TrainersIdRoute: TrainersIdRoute,
  TrainersIndexRoute: TrainersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
